# Kubernetes manifests for ProjetMicro_sans_eureka
# Deployments + Services for: product-service,
# product-composite-service, recommendation-service, review-service
# Notes:
# - images are expected to be built locally with the exact tags used below
# - imagePullPolicy: IfNotPresent to prefer local images on Docker Desktop
# - gateway-service is exposed as NodePort on 30080 so you can test from localhost

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 80
      targetPort: 7002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-composite-deployment
  labels:
    app: product-composite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-composite-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: product-composite-service
    spec:
      containers:
        - name: product-composite-service
          image: product-composite-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

---
apiVersion: v1
kind: Service
metadata:
  name: product-composite-service
spec:
  type: NodePort
  selector:
    app: product-composite-service
  ports:
    - port: 80
      targetPort: 7001
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
  labels:
    app: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: recommendation-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7003
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
    - port: 80
      targetPort: 7003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: review-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7004
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

---
apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - port: 80
      targetPort: 7004
