# Kubernetes manifests for ProjetMicro_sans_eureka
# Deployments + Services for: product-service,
# product-composite-service, recommendation-service, review-service
# Notes:
# - images are expected to be built locally with the exact tags used below
# - imagePullPolicy: IfNotPresent to prefer local images on Docker Desktop
# - gateway-service is exposed as NodePort on 30080 so you can test from localhost

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: projetmicroservice-product-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: NO_PROXY
              value: "product,recommendation,review,mongodb,mysql,kafka,zookeeper,localhost,127.0.0.1,.svc,.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 80
      targetPort: 7002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-composite-deployment
  labels:
    app: product-composite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-composite-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: product-composite-service
    spec:
      containers:
        - name: product-composite-service
          image: projetmicroservice-product-composite-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: NO_PROXY
              value: "product,recommendation,review,mongodb,mysql,kafka,zookeeper,localhost,127.0.0.1,.svc,.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: product-composite-service
spec:
  type: NodePort
  selector:
    app: product-composite-service
  ports:
    - port: 80
      targetPort: 7001
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
  labels:
    app: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: projetmicroservice-recommendation-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7003
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: NO_PROXY
              value: "product,recommendation,review,mongodb,mysql,kafka,zookeeper,localhost,127.0.0.1,.svc,.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
    - port: 80
      targetPort: 7003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: projetmicroservice-review-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7004
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: NO_PROXY
              value: "product,recommendation,review,mongodb,mysql,kafka,zookeeper,localhost,127.0.0.1,.svc,.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - port: 80
      targetPort: 7004

---
# MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017

---
# MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: review_db
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
# Zookeeper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181

---
# Kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.0.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
